const char *help_text =
    "OVERVIEW\n"
    "  xclaim converts one format of a claim-containing token to another.\n"
    "\n"
    "  WARNING: xclaim is not yet complete, so some options don't work, error messages are unclear\n"
    "  there are BUGS and such\n"
    "\n"
    "  The input formats are:\n"
    "    * signed CWTs (COSE signed CBOR map of claims)\n"
    "    * UCCS (unsecured CBOR map of claims)\n"
    "    * The -claim option on the command line\n"
    "\n"
    "  The output formats are:\n"
    "    * signed CWTs\n"
    "    * UCCS\n"
    "    * Bare JSON (default, easy for humans to read)\n"
    "\n"
    "  (Hopefully more formats get added over time)\n"
    "\n"
    "\n"
    "EXAMPLES\n"
    "   Make a simple JSON format token with two claims\n"
    "     xclaim -claim 100:100 -claim ueid:043aff\n"
    "\n"
    "   Make a signed CWT token with one claim\n"
    "     xclaim -claim nonce:ff0039a1 -out_form CBOR -out_prot sign -out_sign_key ec.pem -out tok.cbor\n"
    "\n"
    "   Verify a CWT token and output in JSON\n"
    "     xclaim -in tok.cbor -in_verify_key ec.pem\n"
    "\n"
    "   Turn a UCCS into a signed CWT token\n"
    "     xclaim -in uccs.cbor -out_form CBOR -out_prot sign -out_sign_key ec.pem -out tok.cbor\n"
    "\n"
    "\n"
    "OPTIONS\n"
    "  -claim <ll:vv>               Describes a claim. <ll> is the label. <vv> is the value.\n"
    "                               If <vv> is a binary string like the nonce or ueid,\n"
    "                               it is expressed as hex digits (e.g., ff03a800).\n"
    "                               <ll> may be any integer identifying a standardized\n"
    "                               or registered claim or a claim that is not standard\n"
    "                               or registered. It may also be the text name for\n"
    "                               a standard or registered claim. See list below.\n"
    "\n"
    "  -in <file>                   The input file when -claim is not used.\n"
    "  -in_prot <prot>              The expected protection. One of: none, sign, auto\n"
    "  -in_form <form>              The input format. One of: cbor\n"
    "  -in_verify_key <file>        A PEM format file with a verification key\n"
    "\n"
    "  -out <file>                  The output file. The default is stdout\n"
    "  -out_form <form>             The output format. One of: cbor, json\n"
    "  -out_prot <prot>             The output protection. One of: none, sign\n"
    "  -out_sign_alg <alg>          Alg is one of the COSE signing algorithms\n"
    "  -out_sign_key <file>         Private key to sign with\n"
    "  -out_sign_kid <kid>          Key ID associated with -out_sign_key\n"
    "  -out_sign_certs <file>       Cert to include in the output token for use when verifying\n"
    "  -out_sign_short_circuit      Use short-circuit signature to sign with\n"
    "\n"
    "\n"
    "PLANNED OPTIONS\n"
    "  -in_prot <prot>              The expected protection. One of: none, sign, mac, sign_encrypt, mac_encrypt, auto\n"
    "  -in_form <form>              The input format. One of: cbor, json\n"
    "\n"
    "  -in_verify_cert <cert_file>  Certificates to chain up to\n"
    "  -in_decrypt_key <key_file>   Private key for decryption.\n"
    "  -in_no_verify                The input file will be decoded, but any signature or mac will not be verified. No need to supply key material\n"
    "  -out_encrypt_alg <alg>       Alg is one of the COSE signing algorithms\n"
    "  -out_encrypt_key <file>      Public key to encrypt with\n"
    "  -out_tag <tagging>           CBOR tagging. One of: none, full, cose\n"
    "  -out_prot <prot>             The output protection. One of: none, sign, mac, sign_encrypt, mac_encrypt\n"
    "\n"
    "\n"
    "SUPPORTED CLAIMS (lots more needed. You can help! https://github.com/laurencelundblade/xclaim)\n"
    "  nonce                       The nonce. A binary byte string.\n"
    "  ueid                        Universal Entity ID. A binary byte string.\n"
    "  iss                         The issuer as defined by CWT and JWT. A text string.\n"
    "  sub                         The subject as defined by CWT and JWT. A test string.\n"
    "  aud                         The audience as defined by CWT and JWT. A text string.\n"
    "  exp                         The expiration date as defined by CWT and JWT. An\n"
    "                              integer with the UNIX epoch date (TODO: support other date formats)\n"
    "  nbf                         Not before as defined by CWT and JWT. Same format as exp.\n"
    "  iat                         Issued at as defined by CWT and JWT. The time the token\n"
    "                              as issued. Same format as exp.\n"
    "  cti                         Unique token identifier as defined by CWT. A binary byte string.\n"
    "                              (TODO: support jti)\n"
    "  seclevel                    The EAT security level\n"
    "  secboot                     Whether secure boot is on or off ad defined by EAT.\n"
    "  dbgstat                     The debug status of entity as defined by EAT.\n"
    "  location                    The GPS location as defined by EAT.\n"
    ;
